# Generated by Django 6.0.7 on 2026-07-07 19:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurtainDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='designs/')),
                ('style', models.CharField(choices=[('rod_pocket', 'Rod Pocket'), ('grommet', 'Grommet'), ('pinch_pleat', 'Pinch Pleat'), ('goblet_pleat', 'Goblet Pleat'), ('tab_top', 'Tab Top'), ('eyelet', 'Eyelet'), ('pencil_pleat', 'Pencil Pleat')], max_length=100)),
                ('heading_type', models.CharField(choices=[('standard', 'Standard'), ('double_pleat', 'Double Pleat'), ('triple_pleat', 'Triple Pleat'), ('box_pleat', 'Box Pleat')], max_length=100)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price in Naira', max_digits=10)),
                ('customization_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_customizable', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('has_inner_curtain', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FabricColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hex_code', models.CharField(help_text='Hex color code e.g., #FF0000', max_length=7)),
                ('category', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('exotic', 'Exotic')], max_length=50)),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.0'), help_text='Multiply base price by this value', max_digits=4)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FabricType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price_per_meter', models.DecimalField(decimal_places=2, help_text='Price in Naira per meter', max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='fabrics/')),
                ('is_light_fabric', models.BooleanField(default=False, help_text='Check if this is a light fabric suitable for inner curtains')),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CurtainCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('width', models.DecimalField(decimal_places=2, help_text='Width in inches', max_digits=6, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(240)])),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in inches', max_digits=6, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(240)])),
                ('include_inner_curtain', models.BooleanField(default=False)),
                ('style', models.CharField(choices=[('rod_pocket', 'Rod Pocket'), ('grommet', 'Grommet'), ('pinch_pleat', 'Pinch Pleat'), ('goblet_pleat', 'Goblet Pleat'), ('tab_top', 'Tab Top'), ('eyelet', 'Eyelet'), ('pencil_pleat', 'Pencil Pleat')], max_length=100)),
                ('heading_type', models.CharField(choices=[('standard', 'Standard'), ('double_pleat', 'Double Pleat'), ('triple_pleat', 'Triple Pleat'), ('box_pleat', 'Box Pleat')], max_length=100)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('added_to_cart', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curtains.curtaindesign')),
                ('fabric_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curtains.fabriccolor')),
                ('fabric_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curtains.fabrictype')),
                ('inner_fabric', models.ForeignKey(blank=True, limit_choices_to={'is_light_fabric': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inner_curtains', to='curtains.fabrictype')),
            ],
        ),
        migrations.CreateModel(
            name='ReadyMadeCurtain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.DecimalField(decimal_places=2, max_digits=6)),
                ('height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('includes_inner_curtain', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curtains.curtaindesign')),
                ('fabric_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curtains.fabriccolor')),
                ('fabric_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curtains.fabrictype')),
                ('inner_fabric', models.ForeignKey(blank=True, limit_choices_to={'is_light_fabric': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ready_made_inner', to='curtains.fabrictype')),
            ],
            options={
                'verbose_name': 'Ready-Made Curtain',
                'verbose_name_plural': 'Ready-Made Curtains',
            },
        ),
    ]
