# Generated by Django 6.0.7 on 2026-07-08 00:44

import curtains.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curtains', '0002_heroimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curtaindesign',
            name='image',
            field=models.ImageField(upload_to='designs/', validators=[curtains.models.validate_image_dimensions]),
        ),
        migrations.AlterField(
            model_name='heroimage',
            name='image',
            field=models.ImageField(upload_to='hero_images/', validators=[curtains.models.validate_image_dimensions]),
        ),
    ]
