# Generated by Django 6.0.7 on 2026-07-08 00:51

import curtains.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curtains', '0003_alter_curtaindesign_image_alter_heroimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='readymadecurtain',
            name='image',
            field=models.ImageField(blank=True, help_text="Upload specific image for this curtain, or leave blank to use the design's image.", null=True, upload_to='ready_made/', validators=[curtains.models.validate_image_dimensions]),
        ),
    ]
